config/routes.rb
Rails.application.routes.draw do

    root 'home#index'

    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

    resources :home
    resources :users
    match '/contacts', to: 'contacts#new', via: 'get'
    resources "contacts", only: [:new, :create]
    resource :session

    match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    match 'auth/failure', to: redirect('/'), via: [:get, :post]
    match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

    

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Power Brackets Contact Form",
      :to => "cvangilder64@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :timeoutable and

    validates :name, presence: true
    validates :last_name, presence: true, :unless => :provider?
    validates :email, presence: true, :unless => :provider?
    has_secure_password

    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable,
        :confirmable, :lockable, :omniauthable,
        :omniauth_providers => [:facebook]

    validates :name, presence: true
    validates :last_name, presence: true    , :unless => :provider?
    validates :email, presence: true        , :unless => :provider?

    def self.from_omniauth(auth)
        where(auth.slice(:provider, :uid)).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
            user.name = auth.info.name   # assuming the user model has a name
#            user.provider = auth.provider
#            user.uid = auth.uid
            user.oauth_token = auth.credentials.token
#            user.image = auth.info.image # assuming the user model has an image

            if auth.credentials.expires_at
                user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            end
            user.save!
        end
    end

    def self.new_with_session(params, session)
        super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
                user.email = data["email"] if user.email.blank?
            end
        end
    end
end

app/models/user1.rb
class User < ActiveRecord::Base

    validates :name, presence: true
    validates :last_name, presence: true, :unless => :provider?
    validates :email, presence: true, :unless => :provider?
    has_secure_password

    def self.from_omniauth(auth)
        where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.oauth_token = auth.credentials.token
            if auth.credentials.expires_at
                user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            end
            user.password = SecureRandom.hex
            user.save!
        end
    end
end

app/models/users.rb
class Users < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    private
    def current_user
        User.where(id: session[:user_id]).first
    end

    helper_method :current_user

    def logged_in?
        current_user.present?
    end

    helper_method :logged_in?


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def index

    end

    def show

    end

    def new

    end

    def create
        if env["omniauth.auth"]
            user = User.from_omniauth(env["omniauth.auth"])
            session[:user_id] = user.id
            redirect_to current_user
        else
            user = User.where(email: params[:email]).first
            password = user.valid_password?(params[:password])
          if user && password
                session[:user_id] = user.id
                redirect_to current_user
            else
                flash[:notice] = "Invalid email or password."
                redirect_to new_session_url
            end
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "You've been signed out."
        redirect_to new_session_url
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
            set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :ensure_current_user, except: [:new, :create]

    respond_to :html, :json

    def show
        @user = current_user
        respond_with @user
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(safe_params)
        @user.save
        respond_with @user, location: current_user, action: :new
    end

    def edit
        @user = current_user
    end

    def update
        @user = current_user
        @user.update_attributes(safe_params)
        redirect_to user_url(@user)
    end

    def destroy
        @user = current_user
        @user.destroy
        redirect_to users_url
    end

    private

    def safe_params
    safe_attributes = [
        :name,
        :last_name,
        :email,
        :encrypted_password,
        :password,
        :password_confirmation
    ]
    params.require(:user).permit(*safe_attributes)
    end

    def ensure_current_user
        redirect_to new_session_url unless logged_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="jumbotron">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<!-- This is the start of the First Section / Above the Fold -->
<div class="container-fluid container1" id="logo">
    <div class="jumbotron" >
        <img class="main-logo" alt="Logo" src="/assets/logo.png">

        <div>
            <h1>Turn <span class="red">On</span> your<br> competitive side</h1>
        </div>
        <br>
        <a href="#about">
            <div class="scrollindicator" >
                <img class="scroller" alt="Arrow down" src="/assets/arrow_down.png">
            </div>
        </a>
    </div>
</div>
<div class="texture"></div>
    <!-- Golf Background Image -->
<div class="container-fluid container2"></div>

    <!-- Start of Bracket Section -->
<div class="container-fluid container3"id="about"  ><div class="jumbotron bracketh1"><span class="bracket hidden-xs" ><%= image_tag('bracket.png')%></span>
    <h1>Create and manage your own tournaments!</h1></div></div>
<div class="texture"></div>
    <!-- Football Background Image -->
<div class="container-fluid container4"></div>

    <!-- Start of Notifications Section -->
<div class="container-fluid container3">
<div class="col-md-6 notifications">
    <h1>Notifications</h1>
    <ul>
        <li><h3>Learn about events around you based on your profile and interests</h3></li>
        <li><h3>Invite friends to join your "Team"</h3></li>
        <li><h3>Challenge other teams in you area</h3></li>
        <li><h3>Google Maps integration for tournament / challenge locations</h3></li>

    </ul>


</div>

    <!-- Google Calender -->

    <div class="col-md-6 iframe  hidden-sm hidden-xs">
    <%= image_tag('googlemap.png')%>
    </div>
</div>
   <div class="texture"></div>
    <!-- Baseball Background Image -->
<div class="container-fluid container5"></div>

    <!-- User Team Profile Page Section -->
<div class="container-fluid container3">
<div class="col-md-8 notifications"><span class=""><%=image_tag('profile.png', width: '98%')%></span></div>
    <div class="col-md-4 notifications"><h1 class="profileh1">User / Team Profiles</h1>
    <ul class="hidden-sm hidden-xs">
        <li><h3>Default banners based on your interests</h3></li>
        <li><h3>Keep track of your records / statistics</h3></li>
        <li><h3>Add Photo and Video</h3></li>
        <li><h3>Add Friends (Team) / Rivals</h3></li>
    </ul>
    </div>
</div>
<div class="texture"></div>
    <!-- Soccer Background Image -->
<div class="container-fluid container6"></div>

    <!-- Join the team / Sign Up / Sign In Page -->
<div class="container-fluid container3" id="signup" >
    <div class="col-md-12"><h1 class="teamh1">Join the team!</h1></div>



<div class="col-md-6 col-md-offset-3"><br><h1 class="signuph1">Sign Up</h1>
    <h4 class="signuph4">Connect with your friends and learn about<br> competitions in your area!</h4>
    <br>
    <br>

    <!-- Email Address Input -->
    <form action="/users" accept-charset="UTF08" id="new_user" method="post">
            <%= form_for User.new  do |u| %>
                <!-- Email Address Input -->
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                    <input class="form-control" type="email" placeholder="Email address" name="user[email]" id="user_email">
                </div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <input class="form-control" type="text" placeholder="First Name" id="user_name" name="user[name]">
                    <input class="form-control" type="text" placeholder="Last Name" id="user_last_name" name="user[last_name]">
                </div>
                <!-- Password Input -->
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input class="form-control" type="password" placeholder="Password" id="user_password" name="user[password]">
                    <input class="form-control" type="password" placeholder="Confirm Password" id="user_password_confirmation" name="user[password_confirmation]">
                </div>
                <div id="signupalert" style="display:none" class="alert alert-danger">
                    <p>Error:</p>
                    <span></span>
                </div>
                <!-- Sign Up Button -->
                <button type="submit" class="sign-in-button" name="commit" value="Sign Up Now">Sign Up Now</button>

    <% end %>
</form>
    </div>
</div>
<div class="texture"></div>
    <!-- MLG Background Image -->
 <div class="container-fluid container7"></div>

    <!-- Contact Section -->
<div class="container-fluid container3" id="contact">
<div class="col-md-12">
    <h1 class="contacth1" >Let's Keep in Touch!</h1>
    <h4 class="contacth4 hidden-xs">Thank you for visiting Power Brackets! We hope you found exactly what you were looking for! If you have any questions or comments please feel free to add them in the form below. We look forwarding to improving with each of your suggestions!</h4></div>

    <div class="col-md-6">


        <!-- Name Input -->
    <div class="input-group input-group-lg name">
  <span class="input-group-addon">
    <span class="glyphicon glyphicon-user"></span>
  </span>
  <input class="form-control name" type="text" placeholder="Name">
</div>


    <!-- Email Address Input -->
<div class="input-group input-group-lg">
  <span class="input-group-addon">
    <span class="glyphicon glyphicon-envelope"></span>
  </span>
  <input class="form-control email" type="text" placeholder="Email address">
</div>

    <!-- Subject Input -->
        <div class="input-group input-group-lg">
  <span class="input-group-addon">
    <span class="glyphicon glyphicon-question-sign"></span>
  </span>
  <input class="form-control subject" type="text" placeholder="Subject">
</div>

    <!-- Comments Input -->
    <div class="input-group input-group-lg">
  <span class="input-group-addon">
    <span class="glyphicon glyphicon-pencil"></span>
  </span>
  <textarea style="height:150px; width:100%" class="form-control textarea" type="text" placeholder="Comments"></textarea>
</div>

    <!-- Send Message Button -->
      <button type="submit" class="sign-in-button">Send Message</button>

</div>

    <!-- Contact Info -->
    <div class="col-md-6 hidden-sm hidden-xs">
    <h1 class="contacth1">Contact Info</h1>
     <strong><span style="font-size:20px; margin-right:5px;color:white;" class="glyphicon glyphicon-envelope"></span></strong>
        somethingsomething@something.com
        <br>
        <br>
        <strong><span style="font-size:20px; margin-right:5px;color:white;" class="glyphicon glyphicon-picture"></span></strong>
        1234 W 1789 N St. George Utah 84770
        <br>
        <br>
        <strong><span style="font-size:20px; margin-right:5px;" class="glyphicon glyphicon-phone"></span></strong>
        123-456-7890
    </div>
</div>

    <!-- Basketball Background Image-->

    <div class="texture"></div>

    <div class="container-fluid container8"></div>

    <!-- Pricing Page-->
<div class="container-fluid container3" id="pricing" >
    <br>
    <br>
    <!--    Pricing Title-->
        <h1 class="col-md-12 pricingh1" >Pricing</h1>

    <!--    Price Plans-->
    <div class="pricing" >
        <h1>Free</h1>
        <h3>$0.00</h3>

        <p>5 Free Tournaments</p>
        <p>Add Friends To Your Profile</p>
        <p>Accept Challenges to Compete with those in your area</p>
    </div>
     <div class="pricing">
         <h1>Basic</h1>
         <h3>$2.50 per/month</h3>
        <p>Unlimited Tournament Creation</p>
         <p>Track your statistics for all your sports</p>
         <p>Include a Win / Loss Record to your profile</p>
    </div>
     <div class="pricing">
         <h1>Pro</h1>
         <h3>$3.99 per/month</h3>

         <p>For the competitors that want to add <br> an extra interest to their competition</p>
         <p>Create / Add Money Games to your tournaments</p>

    </div>

    <!--    Price Plan Feature Table-->
<table class="table table-striped col-xl-12 hidden-xs">
<tr>
    <thead>
        <td></td>
    <td>
        Free
    </td>
    <td>Basic
   </td>
    <td>Pro

        </td>
        </thead>
</tr>
    <tr>
        <td>Add Friends</td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
    </tr>
    <tr>
        <td>Accept Challenges</td>
         <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
    </tr>
    <tr>
        <td>Create Tournaments</td>
        <td><span style="color:red;" class="glyphicon glyphicon-remove"></span></td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
    </tr>
    <tr>
    <td>Track Your Statistics</td>
        <td><span style="color:red;" class="glyphicon glyphicon-remove"></span></td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
    </tr>
    <tr>
        <td>Additional Money Games</td>
        <td><span style="color:red;" class="glyphicon glyphicon-remove"></span></td>
        <td><span style="color:red;" class="glyphicon glyphicon-remove"></span></td>
        <td><span style="color:green;" class="glyphicon glyphicon-ok"></span></td>
    </tr>


</table>


<!--    end of content div-->
</div>

<footer class="col-md-12 hidden-sm hidden-xs">
<div class="col-md-3">
    <h5>Services</h5>
    <ul>
        <li>Create Your Own Tournaments</li>
        <li>Connect with athletes in your area</li>
        <li>Track your statistics and improvement</li>
    </ul>
</div>
<div class="col-md-3">
    <h5>Social Media</h5>
<span class="center">
      <%= link_to image_tag('facebookicon.jpg', style: "width:50px;"), 'https://facebook.com/powerbrackets', target: "_blank" %>
        <%= link_to image_tag('twittericon.jpg',style: "width:50px;"), 'https://twitter.com/PWR_Brackets', target: "_blank" %>
       <%= link_to image_tag('instagramicon.jpg',style: "width:50px;"), 'https://instagram.com', target: "_blank" %>
</span>
</div>
<div class="col-md-3">
    <h5>Contact</h5>
    <ul>
      <li>Email:<br> something@something.com</li>
        <li>Address:<br> 1234 E 1234 W St George UT 84770</li>
        <li>Phone: <br>123-456-7890</li>
    </ul>
</div>

<div class="col-md-3">
    <h5>&copy; Copyright Power Brackets 2014</h5>
</div>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>PowerBrackets</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->

</head>
<body>
    <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#logo">
                    <%= image_tag('logo1.png')%>
                </a>
            </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                       <%= link_to "Home", "/#logo" %>

                    </li>
                    <li>
                       <%= link_to "About", "/#about" %>

                    </li>
                    <li>
                       <%= link_to "Contact", "/#contact" %>

                    </li>
                     <li>
                       <%= link_to "Pricing", "/#pricing" %>

                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                   <% if user_signed_in? %>
                       <li><%= link_to current_user.name, current_user %></li>
                   <% else %>
                       <li> <a href="/users/new">Sign Up</a></li>
                   <% end %>
                    <% if current_user %>
                    <li class="dropdown">

                         <button class="btn btn-danger poweron dropdown-toggle" data-toggle="dropdown"><%= link_to "Power Off", session_path, method: :delete %></button>
                        </li>
                    <% else %>
                    <li class="dropdown">
                        <button class="btn btn-danger dropdown-toggle poweron" data-toggle="dropdown">Power On</button>
                        <div id="loginbox" class="dropdown-menu panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">Sign In</div>
                                <div style="float:right; position: relative; top:-15px"><button class="btn btn-link" style="font-size: 85%;" href="#">Forgot password?</button></div>
                            </div>
                            <div class="panel-body">
                                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

<!--                                Dropdown Sign in Form-->

<!--                                <form id="loginform" class="form-signin" role="form">-->
                                   <%= form_tag session_path, method: 'post' do %>
                                   <br>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input id="email" type="text" class="form-control" name="email" value="" placeholder="Email">
                                    </div>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                        <input id="password" type="password" class="form-control" name="password" placeholder="Password">
                                    </div>
                                        <div class="input-group">
                                        <div class="checkbox">
                                            <label>
                                                <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                                            </label>
                                        </div>
                                    </div>
                                        <div class="form-group">
                                        <div class="controls">
                                            <button type="submit" name="commit"class="btn btn-danger">Login</button>
                                            <button id="btn-fblogin" href="#" class="btn btn-primary">Login with Facebook</button>
                                        </div>
                                    </div>
                                        <div style="border-top: 1px solid #888; padding-top:15px; font-size:85%" >
                                        Don't have an account!
                                        <button type="button" class="btn btn-link" style="font-size:100%;" href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                            Sign Up Here
                                        </button>
                                    </div>
                                    <% end %>
<!--                                </form>-->
                            </div>
                        </div>
                        <div id="signupbox" class="dropdown-menu panel panel-default" style="display:none;">
                            <div class="panel-heading">
                                <div class="panel-title">Sign Up</div>
                                    <button id="signinlink" class="btn btn-link" type="button" style="float:right; font-size: 85%; position: relative; top:-15px" onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</button>
                            </div>
                            <div class="panel-body" >


<!--Drop Down Sign Up Form-->

                                <form id="new_user" action="/users" accept-charset="UTF08" method="post" class="form-signup" role="form">
                                    <%= form_for User.new do |u| %>
                                    <br>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                                        <input type="email" class="form-control" name="user[email]" id="user_email" value="" placeholder="Email">
                                    </div>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input type="text" style="border-bottom:none;" class="form-control" name="user[name]" id="user_name" value="" placeholder="First Name">
                                        <input type="text" class="form-control" name="user[last_name]" id="user_last_name" value="" placeholder="Last Name">
                                    </div>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                        <input type="password" class="form-control" name="user[password]" id="user_password" value="" placeholder="Password">
                                        <input type="password" class="form-control" name="user[password_confirmation]" id="user_password_confirmation" value="" placeholder="Confirm Password">
                                    </div>
                                    <div class="form-group">
                                        <button id="btn-signup" type="submit" class="btn btn-danger"  name="commit"><i class="icon-hand-right"></i>Sign Up</button>
                                        <button id="btn-fbsignup" type="button" class="btn btn-primary"><i class="icon-facebook"></i>Sign Up with Facebook</button>
                                    </div>
                                    <div id="signupalert" style="display:none" class="alert alert-danger">
                                        <p>Error:</p>
                                        <span></span>
                                    </div>
                                    <% end %>
                                    <% end%>
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="padding">
        <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
    </div>


    <%= yield %>

    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>

</body>
</html>

app/views/users/show.html.erb
<div class="container-fluid container1">

<!--    sidenav-->
<!--    end sidenav-->

<div class="container">
<div class="row banner">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-4 col-md-3 profile">
                        <img src="http://francis.edu/uploadedImages/Content/Home/Academics/Schools_and_Departments/blank-profile-photo.jpg" alt="" class=" profile img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-6 profile">

                            <strong><%= current_user.name %> <%= current_user.last_name%></strong>
                        <small><i class="glyphicon glyphicon-map-marker">
                        </i><cite title="San Francisco, USA"> No Info Added</cite>
                            <br>
                            <br>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>  <% if current_user.email %>
                       <%= current_user.email%>
                   <% else %>
                      No Info Added
                   <% end %>

                            <br />
                             <br />
                            <i class="glyphicon glyphicon-gift"></i> No Info Added</p></small>
                        <br>



                            <small><i class="glyphicon glyphicon-pencil"></i> <%= link_to 'Edit Info', edit_user_path(@user) %></small>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
     <nav class="nav" role="navigation">
        <ul class="nav navbar-nav navbar-inverse">
         <li class="col-md-offset-4 col-sm-offset-3"><a href="#">Photos</a></li>
             <li><a href="#">Team</a></li>
             <li><a href="#">Tournaments</a></li>
             <li><a href="#">Statistics</a></li>



         </ul>
    </nav>



    <div class="col-md-4"><span class="info"><p><strong>255</strong> <br> Team Members</p></span></div>
    <div class="col-md-4"><span class="info"><p><strong>1.54</strong> <br> Win / Loss %</p></span></div>
    <div class="col-md-4"><span class="info"><p><strong>11</strong> <br> Completed Tournaments</p></span></div>
</div>




</div>